<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Trading_Cards</RootNamespace>
    <UserSecretsId>151d09e2-b2a1-4cad-af5f-f9c0b367022a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.8.0" />
  </ItemGroup>

</Project>
